"""add phone number

Revision ID: 3d95b8a5fbf2
Revises: 27cbfbdcdcbd
Create Date: 2021-11-28 23:22:41.399279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d95b8a5fbf2'
down_revision = '27cbfbdcdcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
