"""removed phoen number

Revision ID: e9d07c0a5e68
Revises: 3d95b8a5fbf2
Create Date: 2021-11-29 00:44:40.004617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d07c0a5e68'
down_revision = '3d95b8a5fbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
